/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.labimo.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Activation service. Represents a row in the &quot;labimo_Activation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.labimo.model.impl.ActivationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.labimo.model.impl.ActivationImpl}.
 * </p>
 *
 * @author wzgong
 * @see Activation
 * @see com.labimo.model.impl.ActivationImpl
 * @see com.labimo.model.impl.ActivationModelImpl
 * @generated
 */
public interface ActivationModel extends BaseModel<Activation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a activation model instance should use the {@link Activation} interface instead.
	 */

	/**
	 * Returns the primary key of this activation.
	 *
	 * @return the primary key of this activation
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this activation.
	 *
	 * @param primaryKey the primary key of this activation
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the activation ID of this activation.
	 *
	 * @return the activation ID of this activation
	 */
	@AutoEscape
	public String getActivationId();

	/**
	 * Sets the activation ID of this activation.
	 *
	 * @param activationId the activation ID of this activation
	 */
	public void setActivationId(String activationId);

	/**
	 * Returns the hardware uuid of this activation.
	 *
	 * @return the hardware uuid of this activation
	 */
	@AutoEscape
	public String getHardwareUuid();

	/**
	 * Sets the hardware uuid of this activation.
	 *
	 * @param hardwareUuid the hardware uuid of this activation
	 */
	public void setHardwareUuid(String hardwareUuid);

	/**
	 * Returns the license uuid of this activation.
	 *
	 * @return the license uuid of this activation
	 */
	@AutoEscape
	public String getLicenseUuid();

	/**
	 * Sets the license uuid of this activation.
	 *
	 * @param licenseUuid the license uuid of this activation
	 */
	public void setLicenseUuid(String licenseUuid);

	/**
	 * Returns the create time of this activation.
	 *
	 * @return the create time of this activation
	 */
	public Date getCreateTime();

	/**
	 * Sets the create time of this activation.
	 *
	 * @param createTime the create time of this activation
	 */
	public void setCreateTime(Date createTime);

	/**
	 * Returns the valid of this activation.
	 *
	 * @return the valid of this activation
	 */
	public boolean getValid();

	/**
	 * Returns <code>true</code> if this activation is valid.
	 *
	 * @return <code>true</code> if this activation is valid; <code>false</code> otherwise
	 */
	public boolean isValid();

	/**
	 * Sets whether this activation is valid.
	 *
	 * @param valid the valid of this activation
	 */
	public void setValid(boolean valid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Activation activation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Activation> toCacheModel();

	@Override
	public Activation toEscapedModel();

	@Override
	public Activation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}