/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.labimo.model;

import com.labimo.service.persistence.LicensePK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the License service. Represents a row in the &quot;license_License&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.labimo.model.impl.LicenseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.labimo.model.impl.LicenseImpl}.
 * </p>
 *
 * @author wzgong
 * @see License
 * @see com.labimo.model.impl.LicenseImpl
 * @see com.labimo.model.impl.LicenseModelImpl
 * @generated
 */
public interface LicenseModel extends BaseModel<License> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a license model instance should use the {@link License} interface instead.
	 */

	/**
	 * Returns the primary key of this license.
	 *
	 * @return the primary key of this license
	 */
	public LicensePK getPrimaryKey();

	/**
	 * Sets the primary key of this license.
	 *
	 * @param primaryKey the primary key of this license
	 */
	public void setPrimaryKey(LicensePK primaryKey);

	/**
	 * Returns the license uuid of this license.
	 *
	 * @return the license uuid of this license
	 */
	@AutoEscape
	public String getLicenseUuid();

	/**
	 * Sets the license uuid of this license.
	 *
	 * @param licenseUuid the license uuid of this license
	 */
	public void setLicenseUuid(String licenseUuid);

	/**
	 * Returns the hardware uuid of this license.
	 *
	 * @return the hardware uuid of this license
	 */
	@AutoEscape
	public String getHardwareUuid();

	/**
	 * Sets the hardware uuid of this license.
	 *
	 * @param hardwareUuid the hardware uuid of this license
	 */
	public void setHardwareUuid(String hardwareUuid);

	/**
	 * Returns the user ID of this license.
	 *
	 * @return the user ID of this license
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this license.
	 *
	 * @param userId the user ID of this license
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this license.
	 *
	 * @return the user uuid of this license
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this license.
	 *
	 * @param userUuid the user uuid of this license
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the content of this license.
	 *
	 * @return the content of this license
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this license.
	 *
	 * @param content the content of this license
	 */
	public void setContent(String content);

	/**
	 * Returns the create date of this license.
	 *
	 * @return the create date of this license
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this license.
	 *
	 * @param createDate the create date of this license
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this license.
	 *
	 * @return the modified date of this license
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this license.
	 *
	 * @param modifiedDate the modified date of this license
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(License license);

	@Override
	public int hashCode();

	@Override
	public CacheModel<License> toCacheModel();

	@Override
	public License toEscapedModel();

	@Override
	public License toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}