/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.labimo.portlet.tincan.model.impl;

import com.labimo.portlet.tincan.model.TincanSubStatement;
import com.labimo.portlet.tincan.model.TincanSubStatementModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the TincanSubStatement service. Represents a row in the &quot;labimo_TincanSubStatement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.labimo.portlet.tincan.model.TincanSubStatementModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TincanSubStatementImpl}.
 * </p>
 *
 * @author wzgong
 * @see TincanSubStatementImpl
 * @see com.labimo.portlet.tincan.model.TincanSubStatement
 * @see com.labimo.portlet.tincan.model.TincanSubStatementModel
 * @generated
 */
public class TincanSubStatementModelImpl extends BaseModelImpl<TincanSubStatement>
	implements TincanSubStatementModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tincan sub statement model instance should use the {@link com.labimo.portlet.tincan.model.TincanSubStatement} interface instead.
	 */
	public static final String TABLE_NAME = "labimo_TincanSubStatement";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "agentId", Types.BIGINT },
			{ "activityId", Types.BIGINT },
			{ "resultId", Types.BIGINT },
			{ "contextId", Types.BIGINT },
			{ "verbId", Types.BIGINT },
			{ "timestamp", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table labimo_TincanSubStatement (id_ LONG not null primary key,agentId LONG,activityId LONG,resultId LONG,contextId LONG,verbId LONG,timestamp DATE null)";
	public static final String TABLE_SQL_DROP = "drop table labimo_TincanSubStatement";
	public static final String ORDER_BY_JPQL = " ORDER BY tincanSubStatement.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY labimo_TincanSubStatement.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.labimo.portlet.tincan.model.TincanSubStatement"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.labimo.portlet.tincan.model.TincanSubStatement"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.labimo.portlet.tincan.model.TincanSubStatement"));

	public TincanSubStatementModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TincanSubStatement.class;
	}

	@Override
	public String getModelClassName() {
		return TincanSubStatement.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("agentId", getAgentId());
		attributes.put("activityId", getActivityId());
		attributes.put("resultId", getResultId());
		attributes.put("contextId", getContextId());
		attributes.put("verbId", getVerbId());
		attributes.put("timestamp", getTimestamp());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long agentId = (Long)attributes.get("agentId");

		if (agentId != null) {
			setAgentId(agentId);
		}

		Long activityId = (Long)attributes.get("activityId");

		if (activityId != null) {
			setActivityId(activityId);
		}

		Long resultId = (Long)attributes.get("resultId");

		if (resultId != null) {
			setResultId(resultId);
		}

		Long contextId = (Long)attributes.get("contextId");

		if (contextId != null) {
			setContextId(contextId);
		}

		Long verbId = (Long)attributes.get("verbId");

		if (verbId != null) {
			setVerbId(verbId);
		}

		Date timestamp = (Date)attributes.get("timestamp");

		if (timestamp != null) {
			setTimestamp(timestamp);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public long getAgentId() {
		return _agentId;
	}

	@Override
	public void setAgentId(long agentId) {
		_agentId = agentId;
	}

	@Override
	public long getActivityId() {
		return _activityId;
	}

	@Override
	public void setActivityId(long activityId) {
		_activityId = activityId;
	}

	@Override
	public long getResultId() {
		return _resultId;
	}

	@Override
	public void setResultId(long resultId) {
		_resultId = resultId;
	}

	@Override
	public long getContextId() {
		return _contextId;
	}

	@Override
	public void setContextId(long contextId) {
		_contextId = contextId;
	}

	@Override
	public long getVerbId() {
		return _verbId;
	}

	@Override
	public void setVerbId(long verbId) {
		_verbId = verbId;
	}

	@Override
	public Date getTimestamp() {
		return _timestamp;
	}

	@Override
	public void setTimestamp(Date timestamp) {
		_timestamp = timestamp;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			TincanSubStatement.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TincanSubStatement toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TincanSubStatement)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TincanSubStatementImpl tincanSubStatementImpl = new TincanSubStatementImpl();

		tincanSubStatementImpl.setId(getId());
		tincanSubStatementImpl.setAgentId(getAgentId());
		tincanSubStatementImpl.setActivityId(getActivityId());
		tincanSubStatementImpl.setResultId(getResultId());
		tincanSubStatementImpl.setContextId(getContextId());
		tincanSubStatementImpl.setVerbId(getVerbId());
		tincanSubStatementImpl.setTimestamp(getTimestamp());

		tincanSubStatementImpl.resetOriginalValues();

		return tincanSubStatementImpl;
	}

	@Override
	public int compareTo(TincanSubStatement tincanSubStatement) {
		long primaryKey = tincanSubStatement.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TincanSubStatement)) {
			return false;
		}

		TincanSubStatement tincanSubStatement = (TincanSubStatement)obj;

		long primaryKey = tincanSubStatement.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<TincanSubStatement> toCacheModel() {
		TincanSubStatementCacheModel tincanSubStatementCacheModel = new TincanSubStatementCacheModel();

		tincanSubStatementCacheModel.id = getId();

		tincanSubStatementCacheModel.agentId = getAgentId();

		tincanSubStatementCacheModel.activityId = getActivityId();

		tincanSubStatementCacheModel.resultId = getResultId();

		tincanSubStatementCacheModel.contextId = getContextId();

		tincanSubStatementCacheModel.verbId = getVerbId();

		Date timestamp = getTimestamp();

		if (timestamp != null) {
			tincanSubStatementCacheModel.timestamp = timestamp.getTime();
		}
		else {
			tincanSubStatementCacheModel.timestamp = Long.MIN_VALUE;
		}

		return tincanSubStatementCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", agentId=");
		sb.append(getAgentId());
		sb.append(", activityId=");
		sb.append(getActivityId());
		sb.append(", resultId=");
		sb.append(getResultId());
		sb.append(", contextId=");
		sb.append(getContextId());
		sb.append(", verbId=");
		sb.append(getVerbId());
		sb.append(", timestamp=");
		sb.append(getTimestamp());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.labimo.portlet.tincan.model.TincanSubStatement");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>agentId</column-name><column-value><![CDATA[");
		sb.append(getAgentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activityId</column-name><column-value><![CDATA[");
		sb.append(getActivityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>resultId</column-name><column-value><![CDATA[");
		sb.append(getResultId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contextId</column-name><column-value><![CDATA[");
		sb.append(getContextId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>verbId</column-name><column-value><![CDATA[");
		sb.append(getVerbId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>timestamp</column-name><column-value><![CDATA[");
		sb.append(getTimestamp());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TincanSubStatement.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			TincanSubStatement.class
		};
	private long _id;
	private long _agentId;
	private long _activityId;
	private long _resultId;
	private long _contextId;
	private long _verbId;
	private Date _timestamp;
	private TincanSubStatement _escapedModel;
}