/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.labimo.portlet.tincan.model.impl;

import com.labimo.portlet.tincan.model.TincanAgentProfile;
import com.labimo.portlet.tincan.model.TincanAgentProfileModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the TincanAgentProfile service. Represents a row in the &quot;labimo_TincanAgentProfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.labimo.portlet.tincan.model.TincanAgentProfileModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TincanAgentProfileImpl}.
 * </p>
 *
 * @author wzgong
 * @see TincanAgentProfileImpl
 * @see com.labimo.portlet.tincan.model.TincanAgentProfile
 * @see com.labimo.portlet.tincan.model.TincanAgentProfileModel
 * @generated
 */
public class TincanAgentProfileModelImpl extends BaseModelImpl<TincanAgentProfile>
	implements TincanAgentProfileModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tincan agent profile model instance should use the {@link com.labimo.portlet.tincan.model.TincanAgentProfile} interface instead.
	 */
	public static final String TABLE_NAME = "labimo_TincanAgentProfile";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "profileId", Types.VARCHAR },
			{ "updated", Types.TIMESTAMP },
			{ "agentId", Types.BIGINT },
			{ "profile", Types.VARCHAR },
			{ "json_profile", Types.VARCHAR },
			{ "content_type", Types.VARCHAR },
			{ "etag", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table labimo_TincanAgentProfile (id_ LONG not null primary key,profileId VARCHAR(75) null,updated DATE null,agentId LONG,profile VARCHAR(75) null,json_profile VARCHAR(75) null,content_type VARCHAR(75) null,etag VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table labimo_TincanAgentProfile";
	public static final String ORDER_BY_JPQL = " ORDER BY tincanAgentProfile.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY labimo_TincanAgentProfile.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.labimo.portlet.tincan.model.TincanAgentProfile"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.labimo.portlet.tincan.model.TincanAgentProfile"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.labimo.portlet.tincan.model.TincanAgentProfile"));

	public TincanAgentProfileModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TincanAgentProfile.class;
	}

	@Override
	public String getModelClassName() {
		return TincanAgentProfile.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("profileId", getProfileId());
		attributes.put("updated", getUpdated());
		attributes.put("agentId", getAgentId());
		attributes.put("profile", getProfile());
		attributes.put("json_profile", getJson_profile());
		attributes.put("content_type", getContent_type());
		attributes.put("etag", getEtag());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String profileId = (String)attributes.get("profileId");

		if (profileId != null) {
			setProfileId(profileId);
		}

		Date updated = (Date)attributes.get("updated");

		if (updated != null) {
			setUpdated(updated);
		}

		Long agentId = (Long)attributes.get("agentId");

		if (agentId != null) {
			setAgentId(agentId);
		}

		String profile = (String)attributes.get("profile");

		if (profile != null) {
			setProfile(profile);
		}

		String json_profile = (String)attributes.get("json_profile");

		if (json_profile != null) {
			setJson_profile(json_profile);
		}

		String content_type = (String)attributes.get("content_type");

		if (content_type != null) {
			setContent_type(content_type);
		}

		String etag = (String)attributes.get("etag");

		if (etag != null) {
			setEtag(etag);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public String getProfileId() {
		if (_profileId == null) {
			return StringPool.BLANK;
		}
		else {
			return _profileId;
		}
	}

	@Override
	public void setProfileId(String profileId) {
		_profileId = profileId;
	}

	@Override
	public Date getUpdated() {
		return _updated;
	}

	@Override
	public void setUpdated(Date updated) {
		_updated = updated;
	}

	@Override
	public long getAgentId() {
		return _agentId;
	}

	@Override
	public void setAgentId(long agentId) {
		_agentId = agentId;
	}

	@Override
	public String getProfile() {
		if (_profile == null) {
			return StringPool.BLANK;
		}
		else {
			return _profile;
		}
	}

	@Override
	public void setProfile(String profile) {
		_profile = profile;
	}

	@Override
	public String getJson_profile() {
		if (_json_profile == null) {
			return StringPool.BLANK;
		}
		else {
			return _json_profile;
		}
	}

	@Override
	public void setJson_profile(String json_profile) {
		_json_profile = json_profile;
	}

	@Override
	public String getContent_type() {
		if (_content_type == null) {
			return StringPool.BLANK;
		}
		else {
			return _content_type;
		}
	}

	@Override
	public void setContent_type(String content_type) {
		_content_type = content_type;
	}

	@Override
	public String getEtag() {
		if (_etag == null) {
			return StringPool.BLANK;
		}
		else {
			return _etag;
		}
	}

	@Override
	public void setEtag(String etag) {
		_etag = etag;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			TincanAgentProfile.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TincanAgentProfile toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TincanAgentProfile)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TincanAgentProfileImpl tincanAgentProfileImpl = new TincanAgentProfileImpl();

		tincanAgentProfileImpl.setId(getId());
		tincanAgentProfileImpl.setProfileId(getProfileId());
		tincanAgentProfileImpl.setUpdated(getUpdated());
		tincanAgentProfileImpl.setAgentId(getAgentId());
		tincanAgentProfileImpl.setProfile(getProfile());
		tincanAgentProfileImpl.setJson_profile(getJson_profile());
		tincanAgentProfileImpl.setContent_type(getContent_type());
		tincanAgentProfileImpl.setEtag(getEtag());

		tincanAgentProfileImpl.resetOriginalValues();

		return tincanAgentProfileImpl;
	}

	@Override
	public int compareTo(TincanAgentProfile tincanAgentProfile) {
		long primaryKey = tincanAgentProfile.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TincanAgentProfile)) {
			return false;
		}

		TincanAgentProfile tincanAgentProfile = (TincanAgentProfile)obj;

		long primaryKey = tincanAgentProfile.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<TincanAgentProfile> toCacheModel() {
		TincanAgentProfileCacheModel tincanAgentProfileCacheModel = new TincanAgentProfileCacheModel();

		tincanAgentProfileCacheModel.id = getId();

		tincanAgentProfileCacheModel.profileId = getProfileId();

		String profileId = tincanAgentProfileCacheModel.profileId;

		if ((profileId != null) && (profileId.length() == 0)) {
			tincanAgentProfileCacheModel.profileId = null;
		}

		Date updated = getUpdated();

		if (updated != null) {
			tincanAgentProfileCacheModel.updated = updated.getTime();
		}
		else {
			tincanAgentProfileCacheModel.updated = Long.MIN_VALUE;
		}

		tincanAgentProfileCacheModel.agentId = getAgentId();

		tincanAgentProfileCacheModel.profile = getProfile();

		String profile = tincanAgentProfileCacheModel.profile;

		if ((profile != null) && (profile.length() == 0)) {
			tincanAgentProfileCacheModel.profile = null;
		}

		tincanAgentProfileCacheModel.json_profile = getJson_profile();

		String json_profile = tincanAgentProfileCacheModel.json_profile;

		if ((json_profile != null) && (json_profile.length() == 0)) {
			tincanAgentProfileCacheModel.json_profile = null;
		}

		tincanAgentProfileCacheModel.content_type = getContent_type();

		String content_type = tincanAgentProfileCacheModel.content_type;

		if ((content_type != null) && (content_type.length() == 0)) {
			tincanAgentProfileCacheModel.content_type = null;
		}

		tincanAgentProfileCacheModel.etag = getEtag();

		String etag = tincanAgentProfileCacheModel.etag;

		if ((etag != null) && (etag.length() == 0)) {
			tincanAgentProfileCacheModel.etag = null;
		}

		return tincanAgentProfileCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", profileId=");
		sb.append(getProfileId());
		sb.append(", updated=");
		sb.append(getUpdated());
		sb.append(", agentId=");
		sb.append(getAgentId());
		sb.append(", profile=");
		sb.append(getProfile());
		sb.append(", json_profile=");
		sb.append(getJson_profile());
		sb.append(", content_type=");
		sb.append(getContent_type());
		sb.append(", etag=");
		sb.append(getEtag());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.labimo.portlet.tincan.model.TincanAgentProfile");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>profileId</column-name><column-value><![CDATA[");
		sb.append(getProfileId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updated</column-name><column-value><![CDATA[");
		sb.append(getUpdated());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>agentId</column-name><column-value><![CDATA[");
		sb.append(getAgentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>profile</column-name><column-value><![CDATA[");
		sb.append(getProfile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>json_profile</column-name><column-value><![CDATA[");
		sb.append(getJson_profile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>content_type</column-name><column-value><![CDATA[");
		sb.append(getContent_type());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>etag</column-name><column-value><![CDATA[");
		sb.append(getEtag());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TincanAgentProfile.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			TincanAgentProfile.class
		};
	private long _id;
	private String _profileId;
	private Date _updated;
	private long _agentId;
	private String _profile;
	private String _json_profile;
	private String _content_type;
	private String _etag;
	private TincanAgentProfile _escapedModel;
}