/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.labimo.portlet.tincan.model.impl;

import com.labimo.portlet.tincan.model.TincanAgent;
import com.labimo.portlet.tincan.model.TincanAgentModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the TincanAgent service. Represents a row in the &quot;labimo_TincanAgent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.labimo.portlet.tincan.model.TincanAgentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TincanAgentImpl}.
 * </p>
 *
 * @author wzgong
 * @see TincanAgentImpl
 * @see com.labimo.portlet.tincan.model.TincanAgent
 * @see com.labimo.portlet.tincan.model.TincanAgentModel
 * @generated
 */
public class TincanAgentModelImpl extends BaseModelImpl<TincanAgent>
	implements TincanAgentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tincan agent model instance should use the {@link com.labimo.portlet.tincan.model.TincanAgent} interface instead.
	 */
	public static final String TABLE_NAME = "labimo_TincanAgent";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "objectType", Types.VARCHAR },
			{ "name", Types.VARCHAR },
			{ "mbox", Types.VARCHAR },
			{ "mbox_sha1sum", Types.VARCHAR },
			{ "openID", Types.VARCHAR },
			{ "oauth_identifier", Types.VARCHAR },
			{ "canonical_version", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table labimo_TincanAgent (id_ LONG not null primary key,objectType VARCHAR(75) null,name VARCHAR(75) null,mbox VARCHAR(75) null,mbox_sha1sum VARCHAR(75) null,openID VARCHAR(75) null,oauth_identifier VARCHAR(75) null,canonical_version BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table labimo_TincanAgent";
	public static final String ORDER_BY_JPQL = " ORDER BY tincanAgent.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY labimo_TincanAgent.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.labimo.portlet.tincan.model.TincanAgent"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.labimo.portlet.tincan.model.TincanAgent"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.labimo.portlet.tincan.model.TincanAgent"));

	public TincanAgentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TincanAgent.class;
	}

	@Override
	public String getModelClassName() {
		return TincanAgent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("objectType", getObjectType());
		attributes.put("name", getName());
		attributes.put("mbox", getMbox());
		attributes.put("mbox_sha1sum", getMbox_sha1sum());
		attributes.put("openID", getOpenID());
		attributes.put("oauth_identifier", getOauth_identifier());
		attributes.put("canonical_version", getCanonical_version());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String objectType = (String)attributes.get("objectType");

		if (objectType != null) {
			setObjectType(objectType);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String mbox = (String)attributes.get("mbox");

		if (mbox != null) {
			setMbox(mbox);
		}

		String mbox_sha1sum = (String)attributes.get("mbox_sha1sum");

		if (mbox_sha1sum != null) {
			setMbox_sha1sum(mbox_sha1sum);
		}

		String openID = (String)attributes.get("openID");

		if (openID != null) {
			setOpenID(openID);
		}

		String oauth_identifier = (String)attributes.get("oauth_identifier");

		if (oauth_identifier != null) {
			setOauth_identifier(oauth_identifier);
		}

		Boolean canonical_version = (Boolean)attributes.get("canonical_version");

		if (canonical_version != null) {
			setCanonical_version(canonical_version);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public String getObjectType() {
		if (_objectType == null) {
			return StringPool.BLANK;
		}
		else {
			return _objectType;
		}
	}

	@Override
	public void setObjectType(String objectType) {
		_objectType = objectType;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getMbox() {
		if (_mbox == null) {
			return StringPool.BLANK;
		}
		else {
			return _mbox;
		}
	}

	@Override
	public void setMbox(String mbox) {
		_mbox = mbox;
	}

	@Override
	public String getMbox_sha1sum() {
		if (_mbox_sha1sum == null) {
			return StringPool.BLANK;
		}
		else {
			return _mbox_sha1sum;
		}
	}

	@Override
	public void setMbox_sha1sum(String mbox_sha1sum) {
		_mbox_sha1sum = mbox_sha1sum;
	}

	@Override
	public String getOpenID() {
		if (_openID == null) {
			return StringPool.BLANK;
		}
		else {
			return _openID;
		}
	}

	@Override
	public void setOpenID(String openID) {
		_openID = openID;
	}

	@Override
	public String getOauth_identifier() {
		if (_oauth_identifier == null) {
			return StringPool.BLANK;
		}
		else {
			return _oauth_identifier;
		}
	}

	@Override
	public void setOauth_identifier(String oauth_identifier) {
		_oauth_identifier = oauth_identifier;
	}

	@Override
	public boolean getCanonical_version() {
		return _canonical_version;
	}

	@Override
	public boolean isCanonical_version() {
		return _canonical_version;
	}

	@Override
	public void setCanonical_version(boolean canonical_version) {
		_canonical_version = canonical_version;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			TincanAgent.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TincanAgent toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TincanAgent)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TincanAgentImpl tincanAgentImpl = new TincanAgentImpl();

		tincanAgentImpl.setId(getId());
		tincanAgentImpl.setObjectType(getObjectType());
		tincanAgentImpl.setName(getName());
		tincanAgentImpl.setMbox(getMbox());
		tincanAgentImpl.setMbox_sha1sum(getMbox_sha1sum());
		tincanAgentImpl.setOpenID(getOpenID());
		tincanAgentImpl.setOauth_identifier(getOauth_identifier());
		tincanAgentImpl.setCanonical_version(getCanonical_version());

		tincanAgentImpl.resetOriginalValues();

		return tincanAgentImpl;
	}

	@Override
	public int compareTo(TincanAgent tincanAgent) {
		long primaryKey = tincanAgent.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TincanAgent)) {
			return false;
		}

		TincanAgent tincanAgent = (TincanAgent)obj;

		long primaryKey = tincanAgent.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<TincanAgent> toCacheModel() {
		TincanAgentCacheModel tincanAgentCacheModel = new TincanAgentCacheModel();

		tincanAgentCacheModel.id = getId();

		tincanAgentCacheModel.objectType = getObjectType();

		String objectType = tincanAgentCacheModel.objectType;

		if ((objectType != null) && (objectType.length() == 0)) {
			tincanAgentCacheModel.objectType = null;
		}

		tincanAgentCacheModel.name = getName();

		String name = tincanAgentCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			tincanAgentCacheModel.name = null;
		}

		tincanAgentCacheModel.mbox = getMbox();

		String mbox = tincanAgentCacheModel.mbox;

		if ((mbox != null) && (mbox.length() == 0)) {
			tincanAgentCacheModel.mbox = null;
		}

		tincanAgentCacheModel.mbox_sha1sum = getMbox_sha1sum();

		String mbox_sha1sum = tincanAgentCacheModel.mbox_sha1sum;

		if ((mbox_sha1sum != null) && (mbox_sha1sum.length() == 0)) {
			tincanAgentCacheModel.mbox_sha1sum = null;
		}

		tincanAgentCacheModel.openID = getOpenID();

		String openID = tincanAgentCacheModel.openID;

		if ((openID != null) && (openID.length() == 0)) {
			tincanAgentCacheModel.openID = null;
		}

		tincanAgentCacheModel.oauth_identifier = getOauth_identifier();

		String oauth_identifier = tincanAgentCacheModel.oauth_identifier;

		if ((oauth_identifier != null) && (oauth_identifier.length() == 0)) {
			tincanAgentCacheModel.oauth_identifier = null;
		}

		tincanAgentCacheModel.canonical_version = getCanonical_version();

		return tincanAgentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", objectType=");
		sb.append(getObjectType());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", mbox=");
		sb.append(getMbox());
		sb.append(", mbox_sha1sum=");
		sb.append(getMbox_sha1sum());
		sb.append(", openID=");
		sb.append(getOpenID());
		sb.append(", oauth_identifier=");
		sb.append(getOauth_identifier());
		sb.append(", canonical_version=");
		sb.append(getCanonical_version());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.labimo.portlet.tincan.model.TincanAgent");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>objectType</column-name><column-value><![CDATA[");
		sb.append(getObjectType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mbox</column-name><column-value><![CDATA[");
		sb.append(getMbox());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mbox_sha1sum</column-name><column-value><![CDATA[");
		sb.append(getMbox_sha1sum());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>openID</column-name><column-value><![CDATA[");
		sb.append(getOpenID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>oauth_identifier</column-name><column-value><![CDATA[");
		sb.append(getOauth_identifier());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>canonical_version</column-name><column-value><![CDATA[");
		sb.append(getCanonical_version());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TincanAgent.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			TincanAgent.class
		};
	private long _id;
	private String _objectType;
	private String _name;
	private String _mbox;
	private String _mbox_sha1sum;
	private String _openID;
	private String _oauth_identifier;
	private boolean _canonical_version;
	private TincanAgent _escapedModel;
}