/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.labimo.portlet.tincan.model.impl;

import com.labimo.portlet.tincan.model.TincanActivityProfile;
import com.labimo.portlet.tincan.model.TincanActivityProfileModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the TincanActivityProfile service. Represents a row in the &quot;labimo_TincanActivityProfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.labimo.portlet.tincan.model.TincanActivityProfileModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TincanActivityProfileImpl}.
 * </p>
 *
 * @author wzgong
 * @see TincanActivityProfileImpl
 * @see com.labimo.portlet.tincan.model.TincanActivityProfile
 * @see com.labimo.portlet.tincan.model.TincanActivityProfileModel
 * @generated
 */
public class TincanActivityProfileModelImpl extends BaseModelImpl<TincanActivityProfile>
	implements TincanActivityProfileModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tincan activity profile model instance should use the {@link com.labimo.portlet.tincan.model.TincanActivityProfile} interface instead.
	 */
	public static final String TABLE_NAME = "labimo_TincanActivityProfile";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "profileId", Types.VARCHAR },
			{ "activityId", Types.VARCHAR },
			{ "jsonProfile", Types.VARCHAR },
			{ "profile", Types.VARCHAR },
			{ "updated", Types.TIMESTAMP },
			{ "content_type", Types.VARCHAR },
			{ "etag", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table labimo_TincanActivityProfile (id_ LONG not null primary key,profileId VARCHAR(75) null,activityId VARCHAR(75) null,jsonProfile VARCHAR(75) null,profile VARCHAR(75) null,updated DATE null,content_type VARCHAR(75) null,etag VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table labimo_TincanActivityProfile";
	public static final String ORDER_BY_JPQL = " ORDER BY tincanActivityProfile.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY labimo_TincanActivityProfile.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.labimo.portlet.tincan.model.TincanActivityProfile"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.labimo.portlet.tincan.model.TincanActivityProfile"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.labimo.portlet.tincan.model.TincanActivityProfile"));

	public TincanActivityProfileModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TincanActivityProfile.class;
	}

	@Override
	public String getModelClassName() {
		return TincanActivityProfile.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("profileId", getProfileId());
		attributes.put("activityId", getActivityId());
		attributes.put("jsonProfile", getJsonProfile());
		attributes.put("profile", getProfile());
		attributes.put("updated", getUpdated());
		attributes.put("content_type", getContent_type());
		attributes.put("etag", getEtag());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String profileId = (String)attributes.get("profileId");

		if (profileId != null) {
			setProfileId(profileId);
		}

		String activityId = (String)attributes.get("activityId");

		if (activityId != null) {
			setActivityId(activityId);
		}

		String jsonProfile = (String)attributes.get("jsonProfile");

		if (jsonProfile != null) {
			setJsonProfile(jsonProfile);
		}

		String profile = (String)attributes.get("profile");

		if (profile != null) {
			setProfile(profile);
		}

		Date updated = (Date)attributes.get("updated");

		if (updated != null) {
			setUpdated(updated);
		}

		String content_type = (String)attributes.get("content_type");

		if (content_type != null) {
			setContent_type(content_type);
		}

		String etag = (String)attributes.get("etag");

		if (etag != null) {
			setEtag(etag);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public String getProfileId() {
		if (_profileId == null) {
			return StringPool.BLANK;
		}
		else {
			return _profileId;
		}
	}

	@Override
	public void setProfileId(String profileId) {
		_profileId = profileId;
	}

	@Override
	public String getActivityId() {
		if (_activityId == null) {
			return StringPool.BLANK;
		}
		else {
			return _activityId;
		}
	}

	@Override
	public void setActivityId(String activityId) {
		_activityId = activityId;
	}

	@Override
	public String getJsonProfile() {
		if (_jsonProfile == null) {
			return StringPool.BLANK;
		}
		else {
			return _jsonProfile;
		}
	}

	@Override
	public void setJsonProfile(String jsonProfile) {
		_jsonProfile = jsonProfile;
	}

	@Override
	public String getProfile() {
		if (_profile == null) {
			return StringPool.BLANK;
		}
		else {
			return _profile;
		}
	}

	@Override
	public void setProfile(String profile) {
		_profile = profile;
	}

	@Override
	public Date getUpdated() {
		return _updated;
	}

	@Override
	public void setUpdated(Date updated) {
		_updated = updated;
	}

	@Override
	public String getContent_type() {
		if (_content_type == null) {
			return StringPool.BLANK;
		}
		else {
			return _content_type;
		}
	}

	@Override
	public void setContent_type(String content_type) {
		_content_type = content_type;
	}

	@Override
	public String getEtag() {
		if (_etag == null) {
			return StringPool.BLANK;
		}
		else {
			return _etag;
		}
	}

	@Override
	public void setEtag(String etag) {
		_etag = etag;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			TincanActivityProfile.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TincanActivityProfile toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TincanActivityProfile)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TincanActivityProfileImpl tincanActivityProfileImpl = new TincanActivityProfileImpl();

		tincanActivityProfileImpl.setId(getId());
		tincanActivityProfileImpl.setProfileId(getProfileId());
		tincanActivityProfileImpl.setActivityId(getActivityId());
		tincanActivityProfileImpl.setJsonProfile(getJsonProfile());
		tincanActivityProfileImpl.setProfile(getProfile());
		tincanActivityProfileImpl.setUpdated(getUpdated());
		tincanActivityProfileImpl.setContent_type(getContent_type());
		tincanActivityProfileImpl.setEtag(getEtag());

		tincanActivityProfileImpl.resetOriginalValues();

		return tincanActivityProfileImpl;
	}

	@Override
	public int compareTo(TincanActivityProfile tincanActivityProfile) {
		long primaryKey = tincanActivityProfile.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TincanActivityProfile)) {
			return false;
		}

		TincanActivityProfile tincanActivityProfile = (TincanActivityProfile)obj;

		long primaryKey = tincanActivityProfile.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<TincanActivityProfile> toCacheModel() {
		TincanActivityProfileCacheModel tincanActivityProfileCacheModel = new TincanActivityProfileCacheModel();

		tincanActivityProfileCacheModel.id = getId();

		tincanActivityProfileCacheModel.profileId = getProfileId();

		String profileId = tincanActivityProfileCacheModel.profileId;

		if ((profileId != null) && (profileId.length() == 0)) {
			tincanActivityProfileCacheModel.profileId = null;
		}

		tincanActivityProfileCacheModel.activityId = getActivityId();

		String activityId = tincanActivityProfileCacheModel.activityId;

		if ((activityId != null) && (activityId.length() == 0)) {
			tincanActivityProfileCacheModel.activityId = null;
		}

		tincanActivityProfileCacheModel.jsonProfile = getJsonProfile();

		String jsonProfile = tincanActivityProfileCacheModel.jsonProfile;

		if ((jsonProfile != null) && (jsonProfile.length() == 0)) {
			tincanActivityProfileCacheModel.jsonProfile = null;
		}

		tincanActivityProfileCacheModel.profile = getProfile();

		String profile = tincanActivityProfileCacheModel.profile;

		if ((profile != null) && (profile.length() == 0)) {
			tincanActivityProfileCacheModel.profile = null;
		}

		Date updated = getUpdated();

		if (updated != null) {
			tincanActivityProfileCacheModel.updated = updated.getTime();
		}
		else {
			tincanActivityProfileCacheModel.updated = Long.MIN_VALUE;
		}

		tincanActivityProfileCacheModel.content_type = getContent_type();

		String content_type = tincanActivityProfileCacheModel.content_type;

		if ((content_type != null) && (content_type.length() == 0)) {
			tincanActivityProfileCacheModel.content_type = null;
		}

		tincanActivityProfileCacheModel.etag = getEtag();

		String etag = tincanActivityProfileCacheModel.etag;

		if ((etag != null) && (etag.length() == 0)) {
			tincanActivityProfileCacheModel.etag = null;
		}

		return tincanActivityProfileCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", profileId=");
		sb.append(getProfileId());
		sb.append(", activityId=");
		sb.append(getActivityId());
		sb.append(", jsonProfile=");
		sb.append(getJsonProfile());
		sb.append(", profile=");
		sb.append(getProfile());
		sb.append(", updated=");
		sb.append(getUpdated());
		sb.append(", content_type=");
		sb.append(getContent_type());
		sb.append(", etag=");
		sb.append(getEtag());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.labimo.portlet.tincan.model.TincanActivityProfile");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>profileId</column-name><column-value><![CDATA[");
		sb.append(getProfileId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activityId</column-name><column-value><![CDATA[");
		sb.append(getActivityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jsonProfile</column-name><column-value><![CDATA[");
		sb.append(getJsonProfile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>profile</column-name><column-value><![CDATA[");
		sb.append(getProfile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updated</column-name><column-value><![CDATA[");
		sb.append(getUpdated());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>content_type</column-name><column-value><![CDATA[");
		sb.append(getContent_type());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>etag</column-name><column-value><![CDATA[");
		sb.append(getEtag());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TincanActivityProfile.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			TincanActivityProfile.class
		};
	private long _id;
	private String _profileId;
	private String _activityId;
	private String _jsonProfile;
	private String _profile;
	private Date _updated;
	private String _content_type;
	private String _etag;
	private TincanActivityProfile _escapedModel;
}