/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.labimo.portlet.tincan.model.impl;

import com.labimo.portlet.tincan.model.Oauth2Endpoint;
import com.labimo.portlet.tincan.service.Oauth2EndpointLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Oauth2Endpoint service. Represents a row in the &quot;labimo_Oauth2Endpoint&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Oauth2EndpointImpl}.
 * </p>
 *
 * @author wzgong
 * @see Oauth2EndpointImpl
 * @see com.labimo.portlet.tincan.model.Oauth2Endpoint
 * @generated
 */
public abstract class Oauth2EndpointBaseImpl extends Oauth2EndpointModelImpl
	implements Oauth2Endpoint {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a oauth2 endpoint model instance should use the {@link Oauth2Endpoint} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			Oauth2EndpointLocalServiceUtil.addOauth2Endpoint(this);
		}
		else {
			Oauth2EndpointLocalServiceUtil.updateOauth2Endpoint(this);
		}
	}
}