/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.labimo.portlet.tincan.model.impl;

import com.labimo.portlet.tincan.model.TincanStatementContext;
import com.labimo.portlet.tincan.service.TincanStatementContextLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the TincanStatementContext service. Represents a row in the &quot;labimo_TincanStatementContext&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TincanStatementContextImpl}.
 * </p>
 *
 * @author wzgong
 * @see TincanStatementContextImpl
 * @see com.labimo.portlet.tincan.model.TincanStatementContext
 * @generated
 */
public abstract class TincanStatementContextBaseImpl
	extends TincanStatementContextModelImpl implements TincanStatementContext {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tincan statement context model instance should use the {@link TincanStatementContext} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			TincanStatementContextLocalServiceUtil.addTincanStatementContext(this);
		}
		else {
			TincanStatementContextLocalServiceUtil.updateTincanStatementContext(this);
		}
	}
}