/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.labimo.portlet.tincan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LiferayUser service. Represents a row in the &quot;labimo_LiferayUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.labimo.portlet.tincan.model.impl.LiferayUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.labimo.portlet.tincan.model.impl.LiferayUserImpl}.
 * </p>
 *
 * @author wzgong
 * @see LiferayUser
 * @see com.labimo.portlet.tincan.model.impl.LiferayUserImpl
 * @see com.labimo.portlet.tincan.model.impl.LiferayUserModelImpl
 * @generated
 */
public interface LiferayUserModel extends BaseModel<LiferayUser> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a liferay user model instance should use the {@link LiferayUser} interface instead.
	 */

	/**
	 * Returns the primary key of this liferay user.
	 *
	 * @return the primary key of this liferay user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this liferay user.
	 *
	 * @param primaryKey the primary key of this liferay user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this liferay user.
	 *
	 * @return the ID of this liferay user
	 */
	public long getId();

	/**
	 * Sets the ID of this liferay user.
	 *
	 * @param id the ID of this liferay user
	 */
	public void setId(long id);

	/**
	 * Returns the liferay user ID of this liferay user.
	 *
	 * @return the liferay user ID of this liferay user
	 */
	public long getLiferayUserId();

	/**
	 * Sets the liferay user ID of this liferay user.
	 *
	 * @param liferayUserId the liferay user ID of this liferay user
	 */
	public void setLiferayUserId(long liferayUserId);

	/**
	 * Returns the liferay user uuid of this liferay user.
	 *
	 * @return the liferay user uuid of this liferay user
	 * @throws SystemException if a system exception occurred
	 */
	public String getLiferayUserUuid() throws SystemException;

	/**
	 * Sets the liferay user uuid of this liferay user.
	 *
	 * @param liferayUserUuid the liferay user uuid of this liferay user
	 */
	public void setLiferayUserUuid(String liferayUserUuid);

	/**
	 * Returns the name of this liferay user.
	 *
	 * @return the name of this liferay user
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this liferay user.
	 *
	 * @param name the name of this liferay user
	 */
	public void setName(String name);

	/**
	 * Returns the preferred audio level of this liferay user.
	 *
	 * @return the preferred audio level of this liferay user
	 */
	public double getPreferredAudioLevel();

	/**
	 * Sets the preferred audio level of this liferay user.
	 *
	 * @param preferredAudioLevel the preferred audio level of this liferay user
	 */
	public void setPreferredAudioLevel(double preferredAudioLevel);

	/**
	 * Returns the preferred language of this liferay user.
	 *
	 * @return the preferred language of this liferay user
	 */
	@AutoEscape
	public String getPreferredLanguage();

	/**
	 * Sets the preferred language of this liferay user.
	 *
	 * @param preferredLanguage the preferred language of this liferay user
	 */
	public void setPreferredLanguage(String preferredLanguage);

	/**
	 * Returns the preferred delivery speed of this liferay user.
	 *
	 * @return the preferred delivery speed of this liferay user
	 */
	public double getPreferredDeliverySpeed();

	/**
	 * Sets the preferred delivery speed of this liferay user.
	 *
	 * @param preferredDeliverySpeed the preferred delivery speed of this liferay user
	 */
	public void setPreferredDeliverySpeed(double preferredDeliverySpeed);

	/**
	 * Returns the preferred audio captioning of this liferay user.
	 *
	 * @return the preferred audio captioning of this liferay user
	 */
	public long getPreferredAudioCaptioning();

	/**
	 * Sets the preferred audio captioning of this liferay user.
	 *
	 * @param preferredAudioCaptioning the preferred audio captioning of this liferay user
	 */
	public void setPreferredAudioCaptioning(long preferredAudioCaptioning);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LiferayUser liferayUser);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LiferayUser> toCacheModel();

	@Override
	public LiferayUser toEscapedModel();

	@Override
	public LiferayUser toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}