/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.labimo.portlet.tincan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LiferayTincanManifestAct service. Represents a row in the &quot;labimo_LiferayTincanManifestAct&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.labimo.portlet.tincan.model.impl.LiferayTincanManifestActModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.labimo.portlet.tincan.model.impl.LiferayTincanManifestActImpl}.
 * </p>
 *
 * @author wzgong
 * @see LiferayTincanManifestAct
 * @see com.labimo.portlet.tincan.model.impl.LiferayTincanManifestActImpl
 * @see com.labimo.portlet.tincan.model.impl.LiferayTincanManifestActModelImpl
 * @generated
 */
public interface LiferayTincanManifestActModel extends BaseModel<LiferayTincanManifestAct> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a liferay tincan manifest act model instance should use the {@link LiferayTincanManifestAct} interface instead.
	 */

	/**
	 * Returns the primary key of this liferay tincan manifest act.
	 *
	 * @return the primary key of this liferay tincan manifest act
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this liferay tincan manifest act.
	 *
	 * @param primaryKey the primary key of this liferay tincan manifest act
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this liferay tincan manifest act.
	 *
	 * @return the ID of this liferay tincan manifest act
	 */
	public long getId();

	/**
	 * Sets the ID of this liferay tincan manifest act.
	 *
	 * @param id the ID of this liferay tincan manifest act
	 */
	public void setId(long id);

	/**
	 * Returns the activity ID of this liferay tincan manifest act.
	 *
	 * @return the activity ID of this liferay tincan manifest act
	 */
	@AutoEscape
	public String getActivityId();

	/**
	 * Sets the activity ID of this liferay tincan manifest act.
	 *
	 * @param activityId the activity ID of this liferay tincan manifest act
	 */
	public void setActivityId(String activityId);

	/**
	 * Returns the name of this liferay tincan manifest act.
	 *
	 * @return the name of this liferay tincan manifest act
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this liferay tincan manifest act.
	 *
	 * @param name the name of this liferay tincan manifest act
	 */
	public void setName(String name);

	/**
	 * Returns the description of this liferay tincan manifest act.
	 *
	 * @return the description of this liferay tincan manifest act
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this liferay tincan manifest act.
	 *
	 * @param description the description of this liferay tincan manifest act
	 */
	public void setDescription(String description);

	/**
	 * Returns the launch of this liferay tincan manifest act.
	 *
	 * @return the launch of this liferay tincan manifest act
	 */
	@AutoEscape
	public String getLaunch();

	/**
	 * Sets the launch of this liferay tincan manifest act.
	 *
	 * @param launch the launch of this liferay tincan manifest act
	 */
	public void setLaunch(String launch);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LiferayTincanManifestAct liferayTincanManifestAct);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LiferayTincanManifestAct> toCacheModel();

	@Override
	public LiferayTincanManifestAct toEscapedModel();

	@Override
	public LiferayTincanManifestAct toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}