/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.labimo.portlet.tincan.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TincanStatementAttachment service. Represents a row in the &quot;labimo_TincanStatementAttachment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.labimo.portlet.tincan.model.impl.TincanStatementAttachmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.labimo.portlet.tincan.model.impl.TincanStatementAttachmentImpl}.
 * </p>
 *
 * @author wzgong
 * @see TincanStatementAttachment
 * @see com.labimo.portlet.tincan.model.impl.TincanStatementAttachmentImpl
 * @see com.labimo.portlet.tincan.model.impl.TincanStatementAttachmentModelImpl
 * @generated
 */
public interface TincanStatementAttachmentModel extends BaseModel<TincanStatementAttachment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tincan statement attachment model instance should use the {@link TincanStatementAttachment} interface instead.
	 */

	/**
	 * Returns the primary key of this tincan statement attachment.
	 *
	 * @return the primary key of this tincan statement attachment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tincan statement attachment.
	 *
	 * @param primaryKey the primary key of this tincan statement attachment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tincan statement attachment.
	 *
	 * @return the ID of this tincan statement attachment
	 */
	public long getId();

	/**
	 * Sets the ID of this tincan statement attachment.
	 *
	 * @param id the ID of this tincan statement attachment
	 */
	public void setId(long id);

	/**
	 * Returns the statement ID of this tincan statement attachment.
	 *
	 * @return the statement ID of this tincan statement attachment
	 */
	public long getStatementId();

	/**
	 * Sets the statement ID of this tincan statement attachment.
	 *
	 * @param statementId the statement ID of this tincan statement attachment
	 */
	public void setStatementId(long statementId);

	/**
	 * Returns the statement attachment ID of this tincan statement attachment.
	 *
	 * @return the statement attachment ID of this tincan statement attachment
	 */
	public long getStatementAttachmentId();

	/**
	 * Sets the statement attachment ID of this tincan statement attachment.
	 *
	 * @param statementAttachmentId the statement attachment ID of this tincan statement attachment
	 */
	public void setStatementAttachmentId(long statementAttachmentId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TincanStatementAttachment tincanStatementAttachment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TincanStatementAttachment> toCacheModel();

	@Override
	public TincanStatementAttachment toEscapedModel();

	@Override
	public TincanStatementAttachment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}