/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.labimo.portlet.tincan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TincanAgentProfile service. Represents a row in the &quot;labimo_TincanAgentProfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.labimo.portlet.tincan.model.impl.TincanAgentProfileModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.labimo.portlet.tincan.model.impl.TincanAgentProfileImpl}.
 * </p>
 *
 * @author wzgong
 * @see TincanAgentProfile
 * @see com.labimo.portlet.tincan.model.impl.TincanAgentProfileImpl
 * @see com.labimo.portlet.tincan.model.impl.TincanAgentProfileModelImpl
 * @generated
 */
public interface TincanAgentProfileModel extends BaseModel<TincanAgentProfile> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tincan agent profile model instance should use the {@link TincanAgentProfile} interface instead.
	 */

	/**
	 * Returns the primary key of this tincan agent profile.
	 *
	 * @return the primary key of this tincan agent profile
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tincan agent profile.
	 *
	 * @param primaryKey the primary key of this tincan agent profile
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tincan agent profile.
	 *
	 * @return the ID of this tincan agent profile
	 */
	public long getId();

	/**
	 * Sets the ID of this tincan agent profile.
	 *
	 * @param id the ID of this tincan agent profile
	 */
	public void setId(long id);

	/**
	 * Returns the profile ID of this tincan agent profile.
	 *
	 * @return the profile ID of this tincan agent profile
	 */
	@AutoEscape
	public String getProfileId();

	/**
	 * Sets the profile ID of this tincan agent profile.
	 *
	 * @param profileId the profile ID of this tincan agent profile
	 */
	public void setProfileId(String profileId);

	/**
	 * Returns the updated of this tincan agent profile.
	 *
	 * @return the updated of this tincan agent profile
	 */
	public Date getUpdated();

	/**
	 * Sets the updated of this tincan agent profile.
	 *
	 * @param updated the updated of this tincan agent profile
	 */
	public void setUpdated(Date updated);

	/**
	 * Returns the agent ID of this tincan agent profile.
	 *
	 * @return the agent ID of this tincan agent profile
	 */
	public long getAgentId();

	/**
	 * Sets the agent ID of this tincan agent profile.
	 *
	 * @param agentId the agent ID of this tincan agent profile
	 */
	public void setAgentId(long agentId);

	/**
	 * Returns the profile of this tincan agent profile.
	 *
	 * @return the profile of this tincan agent profile
	 */
	@AutoEscape
	public String getProfile();

	/**
	 * Sets the profile of this tincan agent profile.
	 *
	 * @param profile the profile of this tincan agent profile
	 */
	public void setProfile(String profile);

	/**
	 * Returns the json_profile of this tincan agent profile.
	 *
	 * @return the json_profile of this tincan agent profile
	 */
	@AutoEscape
	public String getJson_profile();

	/**
	 * Sets the json_profile of this tincan agent profile.
	 *
	 * @param json_profile the json_profile of this tincan agent profile
	 */
	public void setJson_profile(String json_profile);

	/**
	 * Returns the content_type of this tincan agent profile.
	 *
	 * @return the content_type of this tincan agent profile
	 */
	@AutoEscape
	public String getContent_type();

	/**
	 * Sets the content_type of this tincan agent profile.
	 *
	 * @param content_type the content_type of this tincan agent profile
	 */
	public void setContent_type(String content_type);

	/**
	 * Returns the etag of this tincan agent profile.
	 *
	 * @return the etag of this tincan agent profile
	 */
	@AutoEscape
	public String getEtag();

	/**
	 * Sets the etag of this tincan agent profile.
	 *
	 * @param etag the etag of this tincan agent profile
	 */
	public void setEtag(String etag);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TincanAgentProfile tincanAgentProfile);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TincanAgentProfile> toCacheModel();

	@Override
	public TincanAgentProfile toEscapedModel();

	@Override
	public TincanAgentProfile toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}