/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.labimo.portlet.tincan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TincanAttachment service. Represents a row in the &quot;labimo_TincanAttachment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.labimo.portlet.tincan.model.impl.TincanAttachmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.labimo.portlet.tincan.model.impl.TincanAttachmentImpl}.
 * </p>
 *
 * @author wzgong
 * @see TincanAttachment
 * @see com.labimo.portlet.tincan.model.impl.TincanAttachmentImpl
 * @see com.labimo.portlet.tincan.model.impl.TincanAttachmentModelImpl
 * @generated
 */
public interface TincanAttachmentModel extends BaseModel<TincanAttachment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tincan attachment model instance should use the {@link TincanAttachment} interface instead.
	 */

	/**
	 * Returns the primary key of this tincan attachment.
	 *
	 * @return the primary key of this tincan attachment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tincan attachment.
	 *
	 * @param primaryKey the primary key of this tincan attachment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tincan attachment.
	 *
	 * @return the ID of this tincan attachment
	 */
	public long getId();

	/**
	 * Sets the ID of this tincan attachment.
	 *
	 * @param id the ID of this tincan attachment
	 */
	public void setId(long id);

	/**
	 * Returns the usage type of this tincan attachment.
	 *
	 * @return the usage type of this tincan attachment
	 */
	@AutoEscape
	public String getUsageType();

	/**
	 * Sets the usage type of this tincan attachment.
	 *
	 * @param usageType the usage type of this tincan attachment
	 */
	public void setUsageType(String usageType);

	/**
	 * Returns the content type of this tincan attachment.
	 *
	 * @return the content type of this tincan attachment
	 */
	@AutoEscape
	public String getContentType();

	/**
	 * Sets the content type of this tincan attachment.
	 *
	 * @param contentType the content type of this tincan attachment
	 */
	public void setContentType(String contentType);

	/**
	 * Returns the length of this tincan attachment.
	 *
	 * @return the length of this tincan attachment
	 */
	public long getLength();

	/**
	 * Sets the length of this tincan attachment.
	 *
	 * @param length the length of this tincan attachment
	 */
	public void setLength(long length);

	/**
	 * Returns the sha2 of this tincan attachment.
	 *
	 * @return the sha2 of this tincan attachment
	 */
	public long getSha2();

	/**
	 * Sets the sha2 of this tincan attachment.
	 *
	 * @param sha2 the sha2 of this tincan attachment
	 */
	public void setSha2(long sha2);

	/**
	 * Returns the file url of this tincan attachment.
	 *
	 * @return the file url of this tincan attachment
	 */
	@AutoEscape
	public String getFileUrl();

	/**
	 * Sets the file url of this tincan attachment.
	 *
	 * @param fileUrl the file url of this tincan attachment
	 */
	public void setFileUrl(String fileUrl);

	/**
	 * Returns the payload of this tincan attachment.
	 *
	 * @return the payload of this tincan attachment
	 */
	@AutoEscape
	public String getPayload();

	/**
	 * Sets the payload of this tincan attachment.
	 *
	 * @param payload the payload of this tincan attachment
	 */
	public void setPayload(String payload);

	/**
	 * Returns the display of this tincan attachment.
	 *
	 * @return the display of this tincan attachment
	 */
	@AutoEscape
	public String getDisplay();

	/**
	 * Sets the display of this tincan attachment.
	 *
	 * @param display the display of this tincan attachment
	 */
	public void setDisplay(String display);

	/**
	 * Returns the description of this tincan attachment.
	 *
	 * @return the description of this tincan attachment
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this tincan attachment.
	 *
	 * @param description the description of this tincan attachment
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TincanAttachment tincanAttachment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TincanAttachment> toCacheModel();

	@Override
	public TincanAttachment toEscapedModel();

	@Override
	public TincanAttachment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}