/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.labimo.portlet.tincan.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TincanAgent service. Represents a row in the &quot;labimo_TincanAgent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.labimo.portlet.tincan.model.impl.TincanAgentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.labimo.portlet.tincan.model.impl.TincanAgentImpl}.
 * </p>
 *
 * @author wzgong
 * @see TincanAgent
 * @see com.labimo.portlet.tincan.model.impl.TincanAgentImpl
 * @see com.labimo.portlet.tincan.model.impl.TincanAgentModelImpl
 * @generated
 */
public interface TincanAgentModel extends BaseModel<TincanAgent> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tincan agent model instance should use the {@link TincanAgent} interface instead.
	 */

	/**
	 * Returns the primary key of this tincan agent.
	 *
	 * @return the primary key of this tincan agent
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tincan agent.
	 *
	 * @param primaryKey the primary key of this tincan agent
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tincan agent.
	 *
	 * @return the ID of this tincan agent
	 */
	public long getId();

	/**
	 * Sets the ID of this tincan agent.
	 *
	 * @param id the ID of this tincan agent
	 */
	public void setId(long id);

	/**
	 * Returns the object type of this tincan agent.
	 *
	 * @return the object type of this tincan agent
	 */
	@AutoEscape
	public String getObjectType();

	/**
	 * Sets the object type of this tincan agent.
	 *
	 * @param objectType the object type of this tincan agent
	 */
	public void setObjectType(String objectType);

	/**
	 * Returns the name of this tincan agent.
	 *
	 * @return the name of this tincan agent
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this tincan agent.
	 *
	 * @param name the name of this tincan agent
	 */
	public void setName(String name);

	/**
	 * Returns the mbox of this tincan agent.
	 *
	 * @return the mbox of this tincan agent
	 */
	@AutoEscape
	public String getMbox();

	/**
	 * Sets the mbox of this tincan agent.
	 *
	 * @param mbox the mbox of this tincan agent
	 */
	public void setMbox(String mbox);

	/**
	 * Returns the mbox_sha1sum of this tincan agent.
	 *
	 * @return the mbox_sha1sum of this tincan agent
	 */
	@AutoEscape
	public String getMbox_sha1sum();

	/**
	 * Sets the mbox_sha1sum of this tincan agent.
	 *
	 * @param mbox_sha1sum the mbox_sha1sum of this tincan agent
	 */
	public void setMbox_sha1sum(String mbox_sha1sum);

	/**
	 * Returns the open i d of this tincan agent.
	 *
	 * @return the open i d of this tincan agent
	 */
	@AutoEscape
	public String getOpenID();

	/**
	 * Sets the open i d of this tincan agent.
	 *
	 * @param openID the open i d of this tincan agent
	 */
	public void setOpenID(String openID);

	/**
	 * Returns the oauth_identifier of this tincan agent.
	 *
	 * @return the oauth_identifier of this tincan agent
	 */
	@AutoEscape
	public String getOauth_identifier();

	/**
	 * Sets the oauth_identifier of this tincan agent.
	 *
	 * @param oauth_identifier the oauth_identifier of this tincan agent
	 */
	public void setOauth_identifier(String oauth_identifier);

	/**
	 * Returns the canonical_version of this tincan agent.
	 *
	 * @return the canonical_version of this tincan agent
	 */
	public boolean getCanonical_version();

	/**
	 * Returns <code>true</code> if this tincan agent is canonical_version.
	 *
	 * @return <code>true</code> if this tincan agent is canonical_version; <code>false</code> otherwise
	 */
	public boolean isCanonical_version();

	/**
	 * Sets whether this tincan agent is canonical_version.
	 *
	 * @param canonical_version the canonical_version of this tincan agent
	 */
	public void setCanonical_version(boolean canonical_version);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TincanAgent tincanAgent);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TincanAgent> toCacheModel();

	@Override
	public TincanAgent toEscapedModel();

	@Override
	public TincanAgent toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}