/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.labimo.portlet.tincan.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TincanSubStatement service. Represents a row in the &quot;labimo_TincanSubStatement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.labimo.portlet.tincan.model.impl.TincanSubStatementModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.labimo.portlet.tincan.model.impl.TincanSubStatementImpl}.
 * </p>
 *
 * @author wzgong
 * @see TincanSubStatement
 * @see com.labimo.portlet.tincan.model.impl.TincanSubStatementImpl
 * @see com.labimo.portlet.tincan.model.impl.TincanSubStatementModelImpl
 * @generated
 */
public interface TincanSubStatementModel extends BaseModel<TincanSubStatement> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tincan sub statement model instance should use the {@link TincanSubStatement} interface instead.
	 */

	/**
	 * Returns the primary key of this tincan sub statement.
	 *
	 * @return the primary key of this tincan sub statement
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tincan sub statement.
	 *
	 * @param primaryKey the primary key of this tincan sub statement
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tincan sub statement.
	 *
	 * @return the ID of this tincan sub statement
	 */
	public long getId();

	/**
	 * Sets the ID of this tincan sub statement.
	 *
	 * @param id the ID of this tincan sub statement
	 */
	public void setId(long id);

	/**
	 * Returns the agent ID of this tincan sub statement.
	 *
	 * @return the agent ID of this tincan sub statement
	 */
	public long getAgentId();

	/**
	 * Sets the agent ID of this tincan sub statement.
	 *
	 * @param agentId the agent ID of this tincan sub statement
	 */
	public void setAgentId(long agentId);

	/**
	 * Returns the activity ID of this tincan sub statement.
	 *
	 * @return the activity ID of this tincan sub statement
	 */
	public long getActivityId();

	/**
	 * Sets the activity ID of this tincan sub statement.
	 *
	 * @param activityId the activity ID of this tincan sub statement
	 */
	public void setActivityId(long activityId);

	/**
	 * Returns the result ID of this tincan sub statement.
	 *
	 * @return the result ID of this tincan sub statement
	 */
	public long getResultId();

	/**
	 * Sets the result ID of this tincan sub statement.
	 *
	 * @param resultId the result ID of this tincan sub statement
	 */
	public void setResultId(long resultId);

	/**
	 * Returns the context ID of this tincan sub statement.
	 *
	 * @return the context ID of this tincan sub statement
	 */
	public long getContextId();

	/**
	 * Sets the context ID of this tincan sub statement.
	 *
	 * @param contextId the context ID of this tincan sub statement
	 */
	public void setContextId(long contextId);

	/**
	 * Returns the verb ID of this tincan sub statement.
	 *
	 * @return the verb ID of this tincan sub statement
	 */
	public long getVerbId();

	/**
	 * Sets the verb ID of this tincan sub statement.
	 *
	 * @param verbId the verb ID of this tincan sub statement
	 */
	public void setVerbId(long verbId);

	/**
	 * Returns the timestamp of this tincan sub statement.
	 *
	 * @return the timestamp of this tincan sub statement
	 */
	public Date getTimestamp();

	/**
	 * Sets the timestamp of this tincan sub statement.
	 *
	 * @param timestamp the timestamp of this tincan sub statement
	 */
	public void setTimestamp(Date timestamp);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TincanSubStatement tincanSubStatement);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TincanSubStatement> toCacheModel();

	@Override
	public TincanSubStatement toEscapedModel();

	@Override
	public TincanSubStatement toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}